### ISSUE TITLE
Crash loop on server.

### ISSUE THREAD

**Issue by frikinjay** [dmkenza/ClickMachine_Fabric#2]
Puts the server in a crash loop when you try to use the click machine,
1. Face it into a composter.
2. Put it into right click mode.
3. Put bamboo in the machine.
4. Crash loop.

```
Description: Ticking block entity

java.lang.NoClassDefFoundError: net/minecraft/class_310
	at com.kenza.clickmachine.blocks.AutoClickerBlockEntity.getInteractionManager(AutoClickerBlockEntity.kt:66)
	at com.kenza.clickmachine.blocks.AutoClickerBlockEntity.tickRightMode(AutoClickerBlockEntity.kt:224)
	at com.kenza.clickmachine.blocks.AutoClickerBlockEntity.tick(AutoClickerBlockEntity.kt:172)
	at com.kenza.clickmachine.blocks.AutoClickerBlock.getTicker$lambda-1(AutoClickerBlock.kt:78)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:477)
	at net.minecraft.class_3218.method_18765(class_3218.java:365)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.kenza.clickmachine.blocks.AutoClickerBlockEntity.getInteractionManager(AutoClickerBlockEntity.kt:66)
	at com.kenza.clickmachine.blocks.AutoClickerBlockEntity.tickRightMode(AutoClickerBlockEntity.kt:224)
	at com.kenza.clickmachine.blocks.AutoClickerBlockEntity.tick(AutoClickerBlockEntity.kt:172)
	at com.kenza.clickmachine.blocks.AutoClickerBlock.getTicker$lambda-1(AutoClickerBlock.kt:78)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:477)
	at net.minecraft.class_3218.method_18765(class_3218.java:365)

-- Block entity being ticked --
Details:
	Name: clickmachine:auto_clicker // com.kenza.clickmachine.blocks.AutoClickerBlockEntity
	Block: Block{clickmachine:auto_clicker}[active=true,facing=west]
	Block location: World: (967,95,-2868), Section: (at 7,15,12 in 60,5,-180; chunk contains blocks 960,-64,-2880 to 975,319,-2865), Region: (1,-6; contains chunks 32,-192 to 63,-161, blocks 512,-64,-3072 to 1023,319,-2561)
	Block: Block{clickmachine:auto_clicker}[active=true,facing=west]
	Block location: World: (967,95,-2868), Section: (at 7,15,12 in 60,5,-180; chunk contains blocks 960,-64,-2880 to 975,319,-2865), Region: (1,-6; contains chunks 32,-192 to 63,-161, blocks 512,-64,-3072 to 1023,319,-2561)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:477)
	at net.minecraft.class_3218.method_18765(class_3218.java:365)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['frikinjay'/437, l='ServerLevel[world]', x=969.02, y=95.00, z=-2868.15]]
	Chunk stats: 5451
	Level dimension: minecraft:overworld
	Level spawn location: World: (1751,151,-2550), Section: (at 7,7,10 in 109,9,-160; chunk contains blocks 1744,-64,-2560 to 1759,319,-2545), Region: (3,-5; contains chunks 96,-160 to 127,-129, blocks 1536,-64,-2560 to 2047,319,-2049)
	Level time: 14048548 game time, 14893494 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 15518 (now: false), thunder time: 114812 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by dmkenza** [comment]
fixed
