### ISSUE TITLE
crash when placing the machine

### ISSUE THREAD

**Issue by Chuunkyz** [dmkenza/ClickMachine_Fabric#3]
i get a "server closed" message even in singleplayer, and this

---- Minecraft Crash Report ----
// Don't do that.

Time: 1/10/22, 2:40 AM
Description: Ticking block entity

java.lang.NoSuchMethodError: 'void com.kenza.clickmachine.blocks.AutoClickerBlockEntity.tick(net.minecraft.class_2350)'
	at com.kenza.clickmachine.blocks.AutoClickerBlock.getTicker$lambda-2(AutoClickerBlock.kt:82)
	at net.minecraft.world.chunk.WorldChunk$DirectBlockEntityTickInvoker.tick(WorldChunk:659)
	at net.minecraft.world.chunk.WorldChunk$WrappedBlockEntityTickInvoker.tick(WorldChunk:713)
	at net.minecraft.world.World.tickBlockEntities(World:477)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:365)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:879)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:823)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:99)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.kenza.clickmachine.blocks.AutoClickerBlock.getTicker$lambda-2(AutoClickerBlock.kt:82)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:477)
	at net.minecraft.class_3218.method_18765(class_3218.java:365)
Mixins in Stacktrace: Failed to find Mixin metadata: java.lang.NoSuchMethodException: org.spongepowered.asm.mixin.transformer.ClassInfo.getMixins()

-- Block entity being ticked --
Details:
	Name: clickmachine:auto_clicker // com.kenza.clickmachine.blocks.AutoClickerBlockEntity
	Block: Block{clickmachine:auto_clicker}[active=true,facing=west]
	Block location: World: (-709,-46,85), Section: (at 11,2,5 in -45,-3,5; chunk contains blocks -720,-64,80 to -705,319,95), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
	Block: Block{clickmachine:auto_clicker}[active=true,facing=west]
	Block location: World: (-709,-46,85), Section: (at 11,2,5 in -45,-3,5; chunk contains blocks -720,-64,80 to -705,319,95), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
	Block Entity NBT: {Items:[],rightClickMode:0b}
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:477)
	at net.minecraft.class_3218.method_18765(class_3218.java:365)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
Mixins in Stacktrace: Failed to find Mixin metadata: java.lang.NoSuchMethodException: org.spongepowered.asm.mixin.transformer.ClassInfo.getMixins()

**Comment by dmkenza** [comment]
Fixed.
