### ISSUE TITLE
Crash with FTB Teams.

### ISSUE THREAD

**Issue by frikinjay** [dmkenza/ClickMachine_Fabric#4]
Have FTB teams and click machine in the mods folder. Try to use a click machine in a claimed chunk and it crashes.
```
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "dev.ftb.mods.ftbteams.data.PlayerTeam.getExtraData()" because the return value of "dev.ftb.mods.ftbteams.data.TeamManager.getInternalPlayerTeam(java.util.UUID)" is null
	at dev.ftb.mods.ftbchunks.data.ClaimedChunkManager.getBypassProtection(ClaimedChunkManager.java:138)
	at dev.ftb.mods.ftbchunks.data.ClaimedChunkManager.protect(ClaimedChunkManager.java:167)
	at dev.ftb.mods.ftbchunks.FTBChunks.blockRightClick(FTBChunks.java:270)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:54)
	at dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:82)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy137.click(Unknown Source)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$20(EventHandlerImpl.java:77)
	at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41)
	at net.minecraft.class_3225.handler$cfi000$interactBlock(net/fabricmc/fabric/mixin/event/interaction/MixinServerPlayerInteractionManager.java [fabric-events-interaction-v0.mixins.json]:85)
	at net.minecraft.class_3225.method_14262(class_3225.java)
	at com.kenza.clickmachine.blocks.AutoClickerBlockEntity.tickRightMode(AutoClickerBlockEntity.kt:231)
	at com.kenza.clickmachine.blocks.AutoClickerBlockEntity.tick(AutoClickerBlockEntity.kt:179)
	at com.kenza.clickmachine.blocks.AutoClickerBlock.getTicker$lambda-2(AutoClickerBlock.kt:82)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:477)
	at net.minecraft.class_3218.method_18765(class_3218.java:365)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dev.ftb.mods.ftbchunks.data.ClaimedChunkManager.getBypassProtection(ClaimedChunkManager.java:138)
	at dev.ftb.mods.ftbchunks.data.ClaimedChunkManager.protect(ClaimedChunkManager.java:167)
	at dev.ftb.mods.ftbchunks.FTBChunks.blockRightClick(FTBChunks.java:270)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:54)
	at dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:82)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy137.click(Unknown Source)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$20(EventHandlerImpl.java:77)
	at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41)
	at net.minecraft.class_3225.handler$cfi000$interactBlock(net/fabricmc/fabric/mixin/event/interaction/MixinServerPlayerInteractionManager.java [fabric-events-interaction-v0.mixins.json]:85)
	at net.minecraft.class_3225.method_14262(class_3225.java)
	at com.kenza.clickmachine.blocks.AutoClickerBlockEntity.tickRightMode(AutoClickerBlockEntity.kt:231)
	at com.kenza.clickmachine.blocks.AutoClickerBlockEntity.tick(AutoClickerBlockEntity.kt:179)
	at com.kenza.clickmachine.blocks.AutoClickerBlock.getTicker$lambda-2(AutoClickerBlock.kt:82)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:477)
	at net.minecraft.class_3218.method_18765(class_3218.java:365)

-- Block entity being ticked --
Details:
	Name: clickmachine:auto_clicker // com.kenza.clickmachine.blocks.AutoClickerBlockEntity
	Block: Block{clickmachine:auto_clicker}[active=true,facing=east]
	Block location: World: (-50,73,250), Section: (at 14,9,10 in -4,4,15; chunk contains blocks -64,-64,240 to -49,319,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Block: Block{clickmachine:auto_clicker}[active=true,facing=east]
	Block location: World: (-50,73,250), Section: (at 14,9,10 in -4,4,15; chunk contains blocks -64,-64,240 to -49,319,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:477)
	at net.minecraft.class_3218.method_18765(class_3218.java:365)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,73,256), Section: (at 0,9,0 in -2,4,16; chunk contains blocks -32,-64,256 to -17,319,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 459748 game time, 390526 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 102948 (now: false), thunder time: 149720 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by dmkenza** [comment]
Fixed.
