### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by lenigmacedo** [dmkenza/ClickMachine_Fabric#6]
Get crashing on 1.20.1 after put block
Alerady installed kotlin for fabric

**Comment by dmkenza** [comment]
Upload logs please.

**Comment by LokeYourC3PH** [comment]
> Upload logs please.

Here you go:
```
[13/09/2025 16:33:54 pm] ---- Minecraft Crash Report ----
[13/09/2025 16:33:54 pm] // Surprise! Haha. Well, this is awkward.
[13/09/2025 16:33:54 pm] 
[13/09/2025 16:33:54 pm] Time: 2025-09-13 16:33:54
[13/09/2025 16:33:54 pm] Description: Unexpected error
[13/09/2025 16:33:54 pm] 
[13/09/2025 16:33:54 pm] java.lang.IllegalArgumentException: Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.util.math.Direction, values=[north, south, west, east]} to up on Block{clickmachine:auto_clicker}, it is not an allowed value
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.state.State.with(State.java:130)
[13/09/2025 16:33:54 pm] 	at knot//com.kenza.clickmachine.blocks.AutoClickerBlock.getPlacementState(AutoClickerBlock.kt:38)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.item.BlockItem.getPlacementState(BlockItem.java:123)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.item.BlockItem.place(BlockItem.java:75)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.item.BlockItem.useOnBlock(BlockItem.java:50)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.item.ItemStack.useOnBlock(ItemStack.java:272)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.network.ClientPlayerInteractionManager.redirect$cap000$clientsidedcrystals$getActionResult(ClientPlayerInteractionManager.java:3127)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.network.ClientPlayerInteractionManager.interactBlockInternal(ClientPlayerInteractionManager.java:363)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.network.ClientPlayerInteractionManager.method_41933(ClientPlayerInteractionManager.java:324)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.network.ClientPlayerInteractionManager.sendSequencedPacket(ClientPlayerInteractionManager.java:278)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.network.ClientPlayerInteractionManager.interactBlock(ClientPlayerInteractionManager.java:323)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.MinecraftClient.doItemUse(MinecraftClient.java:1802)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.MinecraftClient.accurateblockplacement_DoItemUseBypassDisable(MinecraftClient.java:4011)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.render.GameRenderer.handler$zzb000$accurateblockplacement$onUpdateTargetedEntityComplete(GameRenderer.java:3442)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.render.GameRenderer.updateTargetedEntity(GameRenderer.java:702)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1848)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
[13/09/2025 16:33:54 pm] 	at knot//net.minecraft.client.main.Main.main(Main.java:250)
[13/09/2025 16:33:54 pm] 	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506)
[13/09/2025 16:33:54 pm] 	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
[13/09/2025 16:33:54 pm] 	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[13/09/2025 16:33:54 pm] 
[13/09/2025 16:33:54 pm] 
[13/09/2025 16:33:54 pm] A detailed walkthrough of the error, its code path and all known details is as follows:
[13/09/2025 16:33:54 pm] ---------------------------------------------------------------------------------------
[13/09/2025 16:33:54 pm] 
[13/09/2025 16:33:54 pm] -- Head --
[13/09/2025 16:33:54 pm] Thread: Render thread
[13/09/2025 16:33:54 pm] Stacktrace:
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.state.State.with(State.java:130)
[13/09/2025 16:33:54 pm] 	at knot//com.kenza.clickmachine.blocks.AutoClickerBlock.getPlacementState(AutoClickerBlock.kt:38)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.item.BlockItem.getPlacementState(BlockItem.java:123)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.item.BlockItem.place(BlockItem.java:75)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.item.BlockItem.useOnBlock(BlockItem.java:50)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.item.ItemStack.useOnBlock(ItemStack.java:272)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.network.ClientPlayerInteractionManager.redirect$cap000$clientsidedcrystals$getActionResult(ClientPlayerInteractionManager.java:3127)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.network.ClientPlayerInteractionManager.interactBlockInternal(ClientPlayerInteractionManager.java:363)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.network.ClientPlayerInteractionManager.method_41933(ClientPlayerInteractionManager.java:324)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.network.ClientPlayerInteractionManager.sendSequencedPacket(ClientPlayerInteractionManager.java:278)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.network.ClientPlayerInteractionManager.interactBlock(ClientPlayerInteractionManager.java:323)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.MinecraftClient.doItemUse(MinecraftClient.java:1802)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.MinecraftClient.accurateblockplacement_DoItemUseBypassDisable(MinecraftClient.java:4011)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.render.GameRenderer.handler$zzb000$accurateblockplacement$onUpdateTargetedEntityComplete(GameRenderer.java:3442)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.render.GameRenderer.updateTargetedEntity(GameRenderer.java:702)
[13/09/2025 16:33:54 pm] Mixins in Stacktrace: None found
[13/09/2025 16:33:54 pm] 
[13/09/2025 16:33:54 pm] -- Affected level --
[13/09/2025 16:33:54 pm] Details:
[13/09/2025 16:33:54 pm] 	All players: 1 total; [class_746['**MINECRAFTUSERNAME**'/154, l='ClientWorld minecraft:overworld', x=7674.22, y=65.04, z=-28648.86]]
[13/09/2025 16:33:54 pm] 	Chunk stats: Client Chunks (ImmPtl) 550
[13/09/2025 16:33:54 pm] 	Level dimension: minecraft:overworld
[13/09/2025 16:33:54 pm] 	Level spawn location: World: (64,63,128), Section: (at 0,15,0 in 4,3,8; chunk contains blocks 64,-64,128 to 79,319,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
[13/09/2025 16:33:54 pm] 	Level time: 1414204 game time, 1133932 day time
[13/09/2025 16:33:54 pm] 	Server brand: fabric
[13/09/2025 16:33:54 pm] 	Server type: Non-integrated multiplayer server
[13/09/2025 16:33:54 pm] Stacktrace:
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:458)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2406)
[13/09/2025 16:33:54 pm] 	at knot//MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:826)
[13/09/2025 16:33:54 pm] 	at knot//net.minecraft.client.main.Main.main(Main.java:250)
[13/09/2025 16:33:54 pm] 	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506)
[13/09/2025 16:33:54 pm] 	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
[13/09/2025 16:33:54 pm] 	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[13/09/2025 16:33:54 pm] Mixins in Stacktrace:
[13/09/2025 16:33:54 pm] 	net.minecraft.client.main.Main:
[13/09/2025 16:33:54 pm] 		com.github.getchoo.smoothboot.mixin.client.MainMixin (smoothboot.mixins.json)
[13/09/2025 16:33:54 pm] 		com.periut.cryonicconfig.mixin.client.MainMixin (cryonicconfig.mixins.json)
[13/09/2025 16:33:54 pm] 
[13/09/2025 16:33:54 pm] -- Last reload --
[13/09/2025 16:33:54 pm] Details:
[13/09/2025 16:33:54 pm] 	Reload number: 1
[13/09/2025 16:33:54 pm] 	Reload reason: initial
[13/09/2025 16:33:54 pm] 	Finished: Yes
[13/09/2025 16:33:54 pm] 	Packs: vanilla, fabric, continuity:default, continuity:glass_pane_culling_fix, betterbeds:fancyconnectedbeds, linkedstorage:enderstorage, supplementaries:darker_ropes, file/Round-Trees-7.1-1.19+.zip, file/Foliage+ V1.5.9.3.zip, file/Default-Dark-Mode-1.20-2023.7.0.zip, file/New Villagers!.zip, telepistons:scissor_pistons, Moonlight Mods Dynamic Assets, file/Cave Dweller REANIMATED.zip, file/Dramatic Skys Demo **IPADDRESS**.zip, file/MCBahnschrift.zip, plentyplates:main, file/GiratinaPC.zip, loadmyresources.hiddenpack
[13/09/2025 16:33:54 pm] 
[13/09/2025 16:33:54 pm] -- Cobblemon --
[13/09/2025 16:33:54 pm] Details:
[13/09/2025 16:33:54 pm] 	Version: 1.5.2
[13/09/2025 16:33:54 pm] 	Is Snapshot: false
[13/09/2025 16:33:54 pm] 	Git Commit: df8f078 (https://gitlab.com/cable-mc/cobblemon/-/commit/df8f078d13702ab9a000438910b822ceffbb2248)
[13/09/2025 16:33:54 pm] 	Branch: HEAD
[13/09/2025 16:33:54 pm] 
[13/09/2025 16:33:54 pm] -- System Details --
[13/09/2025 16:33:54 pm] Details:
[13/09/2025 16:33:54 pm] 	Minecraft Version: 1.20.1
[13/09/2025 16:33:54 pm] 	Minecraft Version ID: 1.20.1
[13/09/2025 16:33:54 pm] 	Operating System: Windows 11 (amd64) version 10.0
[13/09/2025 16:33:54 pm] 	Java Version: 21.0.7, Microsoft
[13/09/2025 16:33:54 pm] 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
[13/09/2025 16:33:54 pm] 	Memory: 2698238472 bytes (2573 MiB) / 6039797760 bytes (5760 MiB) up to 17179869184 bytes (16384 MiB)
[13/09/2025 16:33:54 pm] 	CPUs: 16
[13/09/2025 16:33:54 pm] 	Processor Vendor: AuthenticAMD
[13/09/2025 16:33:54 pm] 	Processor Name: AMD Ryzen 7 5700X 8-Core Processor             
[13/09/2025 16:33:54 pm] 	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
[13/09/2025 16:33:54 pm] 	Microarchitecture: Zen 3
[13/09/2025 16:33:54 pm] 	Frequency (GHz): 3.39
[13/09/2025 16:33:54 pm] 	Number of physical packages: 1
[13/09/2025 16:33:54 pm] 	Number of physical CPUs: 8
[13/09/2025 16:33:54 pm] 	Number of logical CPUs: 16
[13/09/2025 16:33:54 pm] 	Graphics card #0 name: Parsec Virtual Display Adapter
[13/09/2025 16:33:54 pm] 	Graphics card #0 vendor: Parsec Cloud, Inc.
[13/09/2025 16:33:54 pm] 	Graphics card #0 VRAM (MB): 0.00
[13/09/2025 16:33:54 pm] 	Graphics card #0 deviceId: unknown
[13/09/2025 16:33:54 pm] 	Graphics card #0 versionInfo: DriverVersion=**IPADDRESS**
[13/09/2025 16:33:54 pm] 	Graphics card #1 name: NVIDIA GeForce RTX 4070 SUPER
[13/09/2025 16:33:54 pm] 	Graphics card #1 vendor: NVIDIA (0x10de)
[13/09/2025 16:33:54 pm] 	Graphics card #1 VRAM (MB): 4095.00
[13/09/2025 16:33:54 pm] 	Graphics card #1 deviceId: 0x2783
[13/09/2025 16:33:54 pm] 	Graphics card #1 versionInfo: DriverVersion=32.0.15.8115
[13/09/2025 16:33:54 pm] 	Memory slot #0 capacity (MB): 16384.00
[13/09/2025 16:33:54 pm] 	Memory slot #0 clockSpeed (GHz): 3.20
[13/09/2025 16:33:54 pm] 	Memory slot #0 type: DDR4
[13/09/2025 16:33:54 pm] 	Memory slot #1 capacity (MB): 16384.00
[13/09/2025 16:33:54 pm] 	Memory slot #1 clockSpeed (GHz): 3.20
[13/09/2025 16:33:54 pm] 	Memory slot #1 type: DDR4
[13/09/2025 16:33:54 pm] 	Memory slot #2 capacity (MB): 16384.00
[13/09/2025 16:33:54 pm] 	Memory slot #2 clockSpeed (GHz): 3.20
[13/09/2025 16:33:54 pm] 	Memory slot #2 type: DDR4
[13/09/2025 16:33:54 pm] 	Memory slot #3 capacity (MB): 16384.00
[13/09/2025 16:33:54 pm] 	Memory slot #3 clockSpeed (GHz): 3.20
[13/09/2025 16:33:54 pm] 	Memory slot #3 type: DDR4
[13/09/2025 16:33:54 pm] 	Virtual memory max (MB): 114616.64
[13/09/2025 16:33:54 pm] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[13/09/2025 16:33:54 pm] If you're having issues, please visit the Discord server for the modpack at https://discord.gg/QtEskhn2d8
[13/09/2025 16:33:54 pm] Checking for updated files!
[13/09/2025 16:33:54 pm] Checking for updates to Modrinth instances
```

Basically crashes when pointing the block up and down, but not north, east, south and west.
